name: breadwinner
favicon: null
layout_spectrum: 0.5147
typography_spectrum: 0.6982105334755033
title: Breadwinner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.125
  lightness: 0.8888796775136143
  saturation: 0.07709008897654712
  rhythmicContrast: 0.7506946395151317
purpose: []
